import { getProgress } from './store';
import { audioFile, audioKey, speakable } from './audioKey';

// Sandboxed/embedded pages can expose speechSynthesis but throw when it is used, so every
// call below is guarded: missing audio must never break a lesson.
function getSynth(): SpeechSynthesis | null {
  try {
    return typeof window !== 'undefined' && 'speechSynthesis' in window ? window.speechSynthesis : null;
  } catch {
    return null;
  }
}
const synth = getSynth();

let voices: SpeechSynthesisVoice[] = [];
const voiceListeners = new Set<() => void>();

function refreshVoices() {
  if (!synth) return;
  try {
    voices = synth.getVoices().filter((v) => v.lang.toLowerCase().startsWith('es'));
  } catch {
    voices = [];
  }
  voiceListeners.forEach((l) => l());
}

if (synth) {
  refreshVoices();
  try {
    synth.addEventListener?.('voiceschanged', refreshVoices);
  } catch {
    // ignore
  }
}

export const speechSupported = () => !!synth;
export const spanishVoices = () => voices;
export function onVoicesChanged(l: () => void) {
  voiceListeners.add(l);
  return () => voiceListeners.delete(l);
}

const QUALITY = /google|natural|neural|premium|enhanced|mónica|monica|paulina|jorge|siri/i;

function pickVoice(): SpeechSynthesisVoice | undefined {
  const { voiceURI, accent } = getProgress().settings;
  const chosen = voices.find((v) => v.voiceURI === voiceURI);
  if (chosen) return chosen;
  const byAccent = accent === 'any' ? voices : voices.filter((v) => v.lang.replace('_', '-').startsWith(accent));
  const pool = byAccent.length ? byAccent : voices;
  // Prefer voices installed on the device: Chrome's online "Google" voices can fail silently.
  const local = pool.filter((v) => v.localService);
  return local.find((v) => QUALITY.test(v.name)) ?? local[0] ?? pool.find((v) => QUALITY.test(v.name)) ?? pool[0];
}

/** Speaks Spanish text. Resolves when finished (or immediately if speech is unavailable). */
// ---- Recorded clips (generated by scripts/generate-audio.ts) -----------------
let clips: Set<string> | null = null;
let clipsLoading: Promise<void> | null = null;
let audioEl: HTMLAudioElement | null = null;

function loadClips(): Promise<void> {
  clipsLoading ??= fetch('./audio/manifest.json')
    .then((r) => (r.ok ? r.json() : []))
    .then((keys: string[]) => { clips = new Set(keys); })
    .catch(() => { clips = new Set(); });
  return clipsLoading;
}
if (typeof window !== 'undefined') void loadClips();

/** Number of natural-voice clips available (0 until audio has been generated). */
export const clipCount = () => clips?.size ?? 0;

function playClip(key: string, rate: number): Promise<boolean> {
  return new Promise((resolve) => {
    try {
      audioEl?.pause();
      const a = new Audio(`./audio/${audioFile(key)}`);
      audioEl = a;
      a.playbackRate = rate;
      a.onended = () => resolve(true);
      a.onerror = () => resolve(false);
      a.play().catch(() => resolve(false));
    } catch {
      resolve(false);
    }
  });
}

export function speak(text: string, opts: { rate?: number; lang?: 'es' | 'en' } = {}): Promise<void> {
  if (opts.lang !== 'en' && getProgress().settings.natural) {
    const key = audioKey(text);
    if (clips?.has(key)) {
      try { synth?.cancel(); } catch { /* ignore */ }
      const rate = Math.max(0.5, Math.min(1.5, (opts.rate ?? getProgress().settings.rate) / 0.9));
      return playClip(key, rate).then((ok) => (ok ? undefined : speakTts(text, opts)));
    }
  }
  return speakTts(text, opts);
}

function speakTts(text: string, opts: { rate?: number; lang?: 'es' | 'en' }): Promise<void> {
  if (!synth) return Promise.resolve();
  return new Promise((resolve) => {
    try {
      speakNow(synth, text, opts, resolve);
    } catch {
      resolve();
    }
  });
}

/** Holding a reference stops Chrome from garbage-collecting the utterance mid-sentence. */
let current: SpeechSynthesisUtterance | null = null;

function speakNow(synth: SpeechSynthesis, text: string, opts: { rate?: number; lang?: 'es' | 'en' }, resolve: () => void) {
  const wasBusy = synth.speaking || synth.pending;
  synth.cancel();
  if (synth.paused) synth.resume();
  const clean = speakable(text);
  const u = new SpeechSynthesisUtterance(clean);
  const rate = opts.lang === 'en' ? 1 : (opts.rate ?? getProgress().settings.rate);
  if (opts.lang === 'en') {
    u.lang = 'en-US';
  } else {
    const voice = pickVoice();
    if (voice) u.voice = voice;
    u.lang = voice?.lang ?? 'es-ES';
  }
  u.rate = rate;
  // Some engines never fire `end` (or have no voices at all); don't let callers hang.
  const timer = setTimeout(done, 1500 + (clean.length * 110) / rate);
  function done() {
    clearTimeout(timer);
    resolve();
  }
  u.onend = done;
  u.onerror = done;
  current = u;
  // Chrome drops an utterance queued in the same tick as cancel(), so give it a moment.
  if (wasBusy) setTimeout(() => current === u && synth.speak(u), 80);
  else synth.speak(u);
}

export function stopSpeaking() {
  audioEl?.pause();
  try {
    synth?.cancel();
  } catch {
    // ignore
  }
}
