import { getProgress } from './store';
import { audioFile, audioKey, speakable } from './audioKey';

// Sandboxed/embedded pages can expose speechSynthesis but throw when it is used, so every
// call below is guarded: missing audio must never break a lesson.
function getSynth(): SpeechSynthesis | null {
  try {
    return typeof window !== 'undefined' && 'speechSynthesis' in window ? window.speechSynthesis : null;
  } catch {
    return null;
  }
}
const synth = getSynth();

let voices: SpeechSynthesisVoice[] = [];
const voiceListeners = new Set<() => void>();

function refreshVoices() {
  if (!synth) return;
  try {
    voices = synth.getVoices().filter((v) => v.lang.toLowerCase().startsWith('es'));
  } catch {
    voices = [];
  }
  voiceListeners.forEach((l) => l());
}

if (synth) {
  refreshVoices();
  try {
    synth.addEventListener?.('voiceschanged', refreshVoices);
  } catch {
    // ignore
  }
}

export const speechSupported = () => !!synth;
export const spanishVoices = () => voices;
export function onVoicesChanged(l: () => void) {
  voiceListeners.add(l);
  return () => voiceListeners.delete(l);
}

const QUALITY = /google|natural|neural|premium|enhanced|mónica|monica|paulina|jorge|siri/i;

function pickVoice(): SpeechSynthesisVoice | undefined {
  const { voiceURI, accent } = getProgress().settings;
  const chosen = voices.find((v) => v.voiceURI === voiceURI);
  if (chosen) return chosen;
  const byAccent = accent === 'any' ? voices : voices.filter((v) => v.lang.replace('_', '-').startsWith(accent));
  const pool = byAccent.length ? byAccent : voices;
  // Prefer voices installed on the device: Chrome's online "Google" voices can fail silently.
  const local = pool.filter((v) => v.localService);
  return local.find((v) => QUALITY.test(v.name)) ?? local[0] ?? pool.find((v) => QUALITY.test(v.name)) ?? pool[0];
}

// ---- Recorded clips (generated by scripts/generate-audio.ts) -----------------
// Spain clips live in public/audio/, other accents in public/audio/<lang>/ (es-US).
type ClipSet = { base: string; keys: Set<string> };
const LANGS = ['es-ES', 'es-US'];
const clipSets: Record<string, ClipSet | null> = {};
let audioEl: HTMLAudioElement | null = null;
/** Resolves the promise of whatever is currently playing (so its button stops "playing"). */
let endCurrent: (() => void) | null = null;

async function loadSet(lang: string) {
  for (const base of lang === 'es-ES' ? ['./audio/'] : [`./audio/${lang}/`]) {
    try {
      const r = await fetch(base + 'manifest.json');
      // The dev server answers unknown paths with index.html, so check it really is JSON.
      if (!r.ok || !(r.headers.get('content-type') ?? '').includes('json')) continue;
      const keys = (await r.json()) as string[];
      if (Array.isArray(keys) && keys.length) {
        clipSets[lang] = { base, keys: new Set(keys) };
        return;
      }
    } catch {
      // no clips for this accent
    }
  }
}
if (typeof window !== 'undefined') LANGS.forEach((l) => void loadSet(l));

/** Clips for the chosen accent, falling back to whichever accent has clips. */
function activeSet(): ClipSet | null {
  const want = getProgress().settings.accent === 'es-MX' ? 'es-US' : 'es-ES';
  return clipSets[want] ?? LANGS.map((l) => clipSets[l]).find(Boolean) ?? null;
}

/** Number of natural-voice clips available for the current accent (0 until generated). */
export const clipCount = () => activeSet()?.keys.size ?? 0;
/** Accent of the clips actually in use, e.g. "es-ES". */
export const clipAccent = () => {
  const set = activeSet();
  return set ? (LANGS.find((l) => clipSets[l] === set) ?? null) : null;
};

function playClip(url: string, rate: number): Promise<boolean> {
  endCurrent?.();
  return new Promise((resolve) => {
    let settled = false;
    const finish = (ok: boolean) => {
      if (settled) return;
      settled = true;
      if (endCurrent === stop) endCurrent = null;
      resolve(ok);
    };
    const stop = () => finish(true);
    endCurrent = stop;
    try {
      audioEl?.pause();
      const a = new Audio(url);
      audioEl = a;
      a.playbackRate = rate;
      a.onended = () => finish(true);
      a.onerror = () => finish(false);
      a.play().catch(() => finish(false));
    } catch {
      finish(false);
    }
  });
}

/** Speaks Spanish text. Resolves when finished (or immediately if speech is unavailable). */
export function speak(text: string, opts: { rate?: number; lang?: 'es' | 'en' } = {}): Promise<void> {
  if (opts.lang !== 'en' && getProgress().settings.natural) {
    const key = audioKey(text);
    const set = activeSet();
    if (set?.keys.has(key)) {
      try { synth?.cancel(); } catch { /* ignore */ }
      const rate = Math.max(0.5, Math.min(1.5, (opts.rate ?? getProgress().settings.rate) / 0.9));
      return playClip(set.base + audioFile(key), rate).then((ok) => (ok ? undefined : speakTts(text, opts)));
    }
  }
  return speakTts(text, opts);
}

function speakTts(text: string, opts: { rate?: number; lang?: 'es' | 'en' }): Promise<void> {
  endCurrent?.();
  audioEl?.pause();
  if (!synth) return Promise.resolve();
  return new Promise((resolve) => {
    try {
      speakNow(synth, text, opts, resolve);
    } catch {
      resolve();
    }
  });
}

/** Holding a reference stops Chrome from garbage-collecting the utterance mid-sentence. */
let current: SpeechSynthesisUtterance | null = null;

function speakNow(synth: SpeechSynthesis, text: string, opts: { rate?: number; lang?: 'es' | 'en' }, resolve: () => void) {
  const wasBusy = synth.speaking || synth.pending;
  synth.cancel();
  if (synth.paused) synth.resume();
  const clean = speakable(text);
  const u = new SpeechSynthesisUtterance(clean);
  const rate = opts.lang === 'en' ? 1 : (opts.rate ?? getProgress().settings.rate);
  if (opts.lang === 'en') {
    u.lang = 'en-US';
  } else {
    const voice = pickVoice();
    if (voice) u.voice = voice;
    u.lang = voice?.lang ?? 'es-ES';
  }
  u.rate = rate;
  // Some engines never fire `end` (or have no voices at all); don't let callers hang.
  const timer = setTimeout(done, 1500 + (clean.length * 110) / rate);
  function done() {
    clearTimeout(timer);
    resolve();
  }
  u.onend = done;
  u.onerror = done;
  let started = false;
  u.onstart = () => { started = true; };
  current = u;
  // Chrome drops an utterance queued in the same tick as cancel(), so give it a moment.
  if (wasBusy) setTimeout(() => current === u && synth.speak(u), 80);
  else synth.speak(u);
  // Chrome on macOS sometimes ignores speak() entirely; if nothing started, try once more.
  setTimeout(() => {
    if (!started && current === u) {
      synth.cancel();
      synth.speak(u);
    }
  }, 900);
}

export function stopSpeaking() {
  audioEl?.pause();
  endCurrent?.();
  try {
    synth?.cancel();
  } catch {
    // ignore
  }
}
